version: '3.8'

services:
  db:
    image: postgres:14
    container_name: tkhm-db-1
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tkhm_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: tkhm-pgadmin-1
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"

#  backend:
#    build: ./backend
#    ports:
#      - "3000:3000"
#    depends_on:
#      - db
#    volumes:
#      - ./backend:/app
#    environment:
#      DATABASE_URL: "postgresql://user:password@db:5432/tkhm_db"

volumes:
  db-data:
  pgadmin-data: 